// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: protos/scoring-service/scoring-service.proto

package scoringpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoredByType int32

const (
	ScoredByType_ORGANIZER ScoredByType = 0
	ScoredByType_ADMIN     ScoredByType = 1
)

// Enum value maps for ScoredByType.
var (
	ScoredByType_name = map[int32]string{
		0: "ORGANIZER",
		1: "ADMIN",
	}
	ScoredByType_value = map[string]int32{
		"ORGANIZER": 0,
		"ADMIN":     1,
	}
)

func (x ScoredByType) Enum() *ScoredByType {
	p := new(ScoredByType)
	*p = x
	return p
}

func (x ScoredByType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScoredByType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_scoring_service_scoring_service_proto_enumTypes[0].Descriptor()
}

func (ScoredByType) Type() protoreflect.EnumType {
	return &file_protos_scoring_service_scoring_service_proto_enumTypes[0]
}

func (x ScoredByType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScoredByType.Descriptor instead.
func (ScoredByType) EnumDescriptor() ([]byte, []int) {
	return file_protos_scoring_service_scoring_service_proto_rawDescGZIP(), []int{0}
}

type Score struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId      string       `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TeamId       string       `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // student qaysi teamda
	UserId       string       `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // kimga baho berilayapti
	Points       int32        `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"`
	Comment      string       `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	ScoredById   string       `protobuf:"bytes,7,opt,name=scored_by_id,json=scoredById,proto3" json:"scored_by_id,omitempty"` // kim berdi
	ScoredByType ScoredByType `protobuf:"varint,8,opt,name=scored_by_type,json=scoredByType,proto3,enum=ScoredByType" json:"scored_by_type,omitempty"`
	CreatedAt    string       `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Score) Reset() {
	*x = Score{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_protos_scoring_service_scoring_service_proto_rawDescGZIP(), []int{0}
}

func (x *Score) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Score) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Score) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Score) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Score) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *Score) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Score) GetScoredById() string {
	if x != nil {
		return x.ScoredById
	}
	return ""
}

func (x *Score) GetScoredByType() ScoredByType {
	if x != nil {
		return x.ScoredByType
	}
	return ScoredByType_ORGANIZER
}

func (x *Score) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GiveScoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId      string       `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TeamId       string       `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId       string       `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // har bir member uchun alohida yuboriladi
	Points       int32        `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`
	Comment      string       `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	ScoredById   string       `protobuf:"bytes,6,opt,name=scored_by_id,json=scoredById,proto3" json:"scored_by_id,omitempty"`
	ScoredByType ScoredByType `protobuf:"varint,7,opt,name=scored_by_type,json=scoredByType,proto3,enum=ScoredByType" json:"scored_by_type,omitempty"`
}

func (x *GiveScoreRequest) Reset() {
	*x = GiveScoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveScoreRequest) ProtoMessage() {}

func (x *GiveScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveScoreRequest.ProtoReflect.Descriptor instead.
func (*GiveScoreRequest) Descriptor() ([]byte, []int) {
	return file_protos_scoring_service_scoring_service_proto_rawDescGZIP(), []int{1}
}

func (x *GiveScoreRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GiveScoreRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *GiveScoreRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GiveScoreRequest) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *GiveScoreRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *GiveScoreRequest) GetScoredById() string {
	if x != nil {
		return x.ScoredById
	}
	return ""
}

func (x *GiveScoreRequest) GetScoredByType() ScoredByType {
	if x != nil {
		return x.ScoredByType
	}
	return ScoredByType_ORGANIZER
}

type GetScoresByEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Limit   int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page    int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetScoresByEventRequest) Reset() {
	*x = GetScoresByEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoresByEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresByEventRequest) ProtoMessage() {}

func (x *GetScoresByEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresByEventRequest.ProtoReflect.Descriptor instead.
func (*GetScoresByEventRequest) Descriptor() ([]byte, []int) {
	return file_protos_scoring_service_scoring_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetScoresByEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetScoresByEventRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetScoresByEventRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetScoresByUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page   int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetScoresByUserRequest) Reset() {
	*x = GetScoresByUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoresByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresByUserRequest) ProtoMessage() {}

func (x *GetScoresByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresByUserRequest.ProtoReflect.Descriptor instead.
func (*GetScoresByUserRequest) Descriptor() ([]byte, []int) {
	return file_protos_scoring_service_scoring_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetScoresByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetScoresByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetScoresByUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetScoresByTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page   int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetScoresByTeamRequest) Reset() {
	*x = GetScoresByTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoresByTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresByTeamRequest) ProtoMessage() {}

func (x *GetScoresByTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresByTeamRequest.ProtoReflect.Descriptor instead.
func (*GetScoresByTeamRequest) Descriptor() ([]byte, []int) {
	return file_protos_scoring_service_scoring_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetScoresByTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *GetScoresByTeamRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetScoresByTeamRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetGlobalRankingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page  int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetGlobalRankingRequest) Reset() {
	*x = GetGlobalRankingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGlobalRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalRankingRequest) ProtoMessage() {}

func (x *GetGlobalRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalRankingRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalRankingRequest) Descriptor() ([]byte, []int) {
	return file_protos_scoring_service_scoring_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetGlobalRankingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetGlobalRankingRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ScoreList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scores     []*Score `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	TotalCount int32    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ScoreList) Reset() {
	*x = ScoreList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreList) ProtoMessage() {}

func (x *ScoreList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreList.ProtoReflect.Descriptor instead.
func (*ScoreList) Descriptor() ([]byte, []int) {
	return file_protos_scoring_service_scoring_service_proto_rawDescGZIP(), []int{6}
}

func (x *ScoreList) GetScores() []*Score {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *ScoreList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Ranking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName    string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	TotalPoints int32  `protobuf:"varint,3,opt,name=total_points,json=totalPoints,proto3" json:"total_points,omitempty"`
	Rank        int32  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *Ranking) Reset() {
	*x = Ranking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ranking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ranking) ProtoMessage() {}

func (x *Ranking) ProtoReflect() protoreflect.Message {
	mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ranking.ProtoReflect.Descriptor instead.
func (*Ranking) Descriptor() ([]byte, []int) {
	return file_protos_scoring_service_scoring_service_proto_rawDescGZIP(), []int{7}
}

func (x *Ranking) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Ranking) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Ranking) GetTotalPoints() int32 {
	if x != nil {
		return x.TotalPoints
	}
	return 0
}

func (x *Ranking) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type RankingList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rankings   []*Ranking `protobuf:"bytes,1,rep,name=rankings,proto3" json:"rankings,omitempty"`
	TotalCount int32      `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *RankingList) Reset() {
	*x = RankingList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingList) ProtoMessage() {}

func (x *RankingList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_scoring_service_scoring_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingList.ProtoReflect.Descriptor instead.
func (*RankingList) Descriptor() ([]byte, []int) {
	return file_protos_scoring_service_scoring_service_proto_rawDescGZIP(), []int{8}
}

func (x *RankingList) GetRankings() []*Ranking {
	if x != nil {
		return x.Rankings
	}
	return nil
}

func (x *RankingList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_protos_scoring_service_scoring_service_proto protoreflect.FileDescriptor

var file_protos_scoring_service_scoring_service_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c,
	0x02, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x64, 0x5f, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x64, 0x42, 0x79, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x0e, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0d, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x64, 0x42, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x64, 0x42, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xe8, 0x01,
	0x0a, 0x10, 0x47, 0x69, 0x76, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x64, 0x42,
	0x79, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x0e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x64, 0x5f, 0x62, 0x79,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x64, 0x42, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x64, 0x42, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0x5e, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x42, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x5b, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x5b, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x73, 0x42, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x22, 0x43, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x52,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a, 0x09, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x06, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x76, 0x0a, 0x07, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e,
	0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x54, 0x0a,
	0x0b, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x08,
	0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x2a, 0x28, 0x0a, 0x0c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x64, 0x42, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x52, 0x47, 0x41, 0x4e, 0x49, 0x5a, 0x45, 0x52,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x01, 0x32, 0x9e, 0x02,
	0x0a, 0x0e, 0x53, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x26, 0x0a, 0x09, 0x47, 0x69, 0x76, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x11, 0x2e,
	0x47, 0x69, 0x76, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x06, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x38, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x42, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x42, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x36, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a,
	0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x42, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x42, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x3a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x52,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0c, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x16,
	0x5a, 0x14, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x6f,
	0x72, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_scoring_service_scoring_service_proto_rawDescOnce sync.Once
	file_protos_scoring_service_scoring_service_proto_rawDescData = file_protos_scoring_service_scoring_service_proto_rawDesc
)

func file_protos_scoring_service_scoring_service_proto_rawDescGZIP() []byte {
	file_protos_scoring_service_scoring_service_proto_rawDescOnce.Do(func() {
		file_protos_scoring_service_scoring_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_scoring_service_scoring_service_proto_rawDescData)
	})
	return file_protos_scoring_service_scoring_service_proto_rawDescData
}

var file_protos_scoring_service_scoring_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_scoring_service_scoring_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_scoring_service_scoring_service_proto_goTypes = []any{
	(ScoredByType)(0),               // 0: ScoredByType
	(*Score)(nil),                   // 1: Score
	(*GiveScoreRequest)(nil),        // 2: GiveScoreRequest
	(*GetScoresByEventRequest)(nil), // 3: GetScoresByEventRequest
	(*GetScoresByUserRequest)(nil),  // 4: GetScoresByUserRequest
	(*GetScoresByTeamRequest)(nil),  // 5: GetScoresByTeamRequest
	(*GetGlobalRankingRequest)(nil), // 6: GetGlobalRankingRequest
	(*ScoreList)(nil),               // 7: ScoreList
	(*Ranking)(nil),                 // 8: Ranking
	(*RankingList)(nil),             // 9: RankingList
}
var file_protos_scoring_service_scoring_service_proto_depIdxs = []int32{
	0, // 0: Score.scored_by_type:type_name -> ScoredByType
	0, // 1: GiveScoreRequest.scored_by_type:type_name -> ScoredByType
	1, // 2: ScoreList.scores:type_name -> Score
	8, // 3: RankingList.rankings:type_name -> Ranking
	2, // 4: ScoringService.GiveScore:input_type -> GiveScoreRequest
	3, // 5: ScoringService.GetScoresByEvent:input_type -> GetScoresByEventRequest
	4, // 6: ScoringService.GetScoresByUser:input_type -> GetScoresByUserRequest
	5, // 7: ScoringService.GetScoresByTeam:input_type -> GetScoresByTeamRequest
	6, // 8: ScoringService.GetGlobalRanking:input_type -> GetGlobalRankingRequest
	1, // 9: ScoringService.GiveScore:output_type -> Score
	7, // 10: ScoringService.GetScoresByEvent:output_type -> ScoreList
	7, // 11: ScoringService.GetScoresByUser:output_type -> ScoreList
	7, // 12: ScoringService.GetScoresByTeam:output_type -> ScoreList
	9, // 13: ScoringService.GetGlobalRanking:output_type -> RankingList
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_scoring_service_scoring_service_proto_init() }
func file_protos_scoring_service_scoring_service_proto_init() {
	if File_protos_scoring_service_scoring_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_scoring_service_scoring_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Score); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_scoring_service_scoring_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GiveScoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_scoring_service_scoring_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetScoresByEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_scoring_service_scoring_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetScoresByUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_scoring_service_scoring_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetScoresByTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_scoring_service_scoring_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetGlobalRankingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_scoring_service_scoring_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ScoreList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_scoring_service_scoring_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Ranking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_scoring_service_scoring_service_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*RankingList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_scoring_service_scoring_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_scoring_service_scoring_service_proto_goTypes,
		DependencyIndexes: file_protos_scoring_service_scoring_service_proto_depIdxs,
		EnumInfos:         file_protos_scoring_service_scoring_service_proto_enumTypes,
		MessageInfos:      file_protos_scoring_service_scoring_service_proto_msgTypes,
	}.Build()
	File_protos_scoring_service_scoring_service_proto = out.File
	file_protos_scoring_service_scoring_service_proto_rawDesc = nil
	file_protos_scoring_service_scoring_service_proto_goTypes = nil
	file_protos_scoring_service_scoring_service_proto_depIdxs = nil
}
