// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: protos/scoring-service/scoring-service.proto

package scoringpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ScoringService_GiveScore_FullMethodName        = "/ScoringService/GiveScore"
	ScoringService_GetScoresByEvent_FullMethodName = "/ScoringService/GetScoresByEvent"
	ScoringService_GetScoresByUser_FullMethodName  = "/ScoringService/GetScoresByUser"
	ScoringService_GetScoresByTeam_FullMethodName  = "/ScoringService/GetScoresByTeam"
	ScoringService_GetGlobalRanking_FullMethodName = "/ScoringService/GetGlobalRanking"
)

// ScoringServiceClient is the client API for ScoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScoringServiceClient interface {
	GiveScore(ctx context.Context, in *GiveScoreRequest, opts ...grpc.CallOption) (*Score, error)
	GetScoresByEvent(ctx context.Context, in *GetScoresByEventRequest, opts ...grpc.CallOption) (*ScoreList, error)
	GetScoresByUser(ctx context.Context, in *GetScoresByUserRequest, opts ...grpc.CallOption) (*ScoreList, error)
	GetScoresByTeam(ctx context.Context, in *GetScoresByTeamRequest, opts ...grpc.CallOption) (*ScoreList, error)
	GetGlobalRanking(ctx context.Context, in *GetGlobalRankingRequest, opts ...grpc.CallOption) (*RankingList, error)
}

type scoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScoringServiceClient(cc grpc.ClientConnInterface) ScoringServiceClient {
	return &scoringServiceClient{cc}
}

func (c *scoringServiceClient) GiveScore(ctx context.Context, in *GiveScoreRequest, opts ...grpc.CallOption) (*Score, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Score)
	err := c.cc.Invoke(ctx, ScoringService_GiveScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetScoresByEvent(ctx context.Context, in *GetScoresByEventRequest, opts ...grpc.CallOption) (*ScoreList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreList)
	err := c.cc.Invoke(ctx, ScoringService_GetScoresByEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetScoresByUser(ctx context.Context, in *GetScoresByUserRequest, opts ...grpc.CallOption) (*ScoreList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreList)
	err := c.cc.Invoke(ctx, ScoringService_GetScoresByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetScoresByTeam(ctx context.Context, in *GetScoresByTeamRequest, opts ...grpc.CallOption) (*ScoreList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreList)
	err := c.cc.Invoke(ctx, ScoringService_GetScoresByTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetGlobalRanking(ctx context.Context, in *GetGlobalRankingRequest, opts ...grpc.CallOption) (*RankingList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankingList)
	err := c.cc.Invoke(ctx, ScoringService_GetGlobalRanking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScoringServiceServer is the server API for ScoringService service.
// All implementations must embed UnimplementedScoringServiceServer
// for forward compatibility
type ScoringServiceServer interface {
	GiveScore(context.Context, *GiveScoreRequest) (*Score, error)
	GetScoresByEvent(context.Context, *GetScoresByEventRequest) (*ScoreList, error)
	GetScoresByUser(context.Context, *GetScoresByUserRequest) (*ScoreList, error)
	GetScoresByTeam(context.Context, *GetScoresByTeamRequest) (*ScoreList, error)
	GetGlobalRanking(context.Context, *GetGlobalRankingRequest) (*RankingList, error)
	mustEmbedUnimplementedScoringServiceServer()
}

// UnimplementedScoringServiceServer must be embedded to have forward compatible implementations.
type UnimplementedScoringServiceServer struct {
}

func (UnimplementedScoringServiceServer) GiveScore(context.Context, *GiveScoreRequest) (*Score, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GiveScore not implemented")
}
func (UnimplementedScoringServiceServer) GetScoresByEvent(context.Context, *GetScoresByEventRequest) (*ScoreList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScoresByEvent not implemented")
}
func (UnimplementedScoringServiceServer) GetScoresByUser(context.Context, *GetScoresByUserRequest) (*ScoreList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScoresByUser not implemented")
}
func (UnimplementedScoringServiceServer) GetScoresByTeam(context.Context, *GetScoresByTeamRequest) (*ScoreList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScoresByTeam not implemented")
}
func (UnimplementedScoringServiceServer) GetGlobalRanking(context.Context, *GetGlobalRankingRequest) (*RankingList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobalRanking not implemented")
}
func (UnimplementedScoringServiceServer) mustEmbedUnimplementedScoringServiceServer() {}

// UnsafeScoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScoringServiceServer will
// result in compilation errors.
type UnsafeScoringServiceServer interface {
	mustEmbedUnimplementedScoringServiceServer()
}

func RegisterScoringServiceServer(s grpc.ServiceRegistrar, srv ScoringServiceServer) {
	s.RegisterService(&ScoringService_ServiceDesc, srv)
}

func _ScoringService_GiveScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GiveScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GiveScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GiveScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GiveScore(ctx, req.(*GiveScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_GetScoresByEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoresByEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetScoresByEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GetScoresByEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GetScoresByEvent(ctx, req.(*GetScoresByEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_GetScoresByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoresByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetScoresByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GetScoresByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GetScoresByUser(ctx, req.(*GetScoresByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_GetScoresByTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoresByTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetScoresByTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GetScoresByTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GetScoresByTeam(ctx, req.(*GetScoresByTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_GetGlobalRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetGlobalRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GetGlobalRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GetGlobalRanking(ctx, req.(*GetGlobalRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScoringService_ServiceDesc is the grpc.ServiceDesc for ScoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ScoringService",
	HandlerType: (*ScoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GiveScore",
			Handler:    _ScoringService_GiveScore_Handler,
		},
		{
			MethodName: "GetScoresByEvent",
			Handler:    _ScoringService_GetScoresByEvent_Handler,
		},
		{
			MethodName: "GetScoresByUser",
			Handler:    _ScoringService_GetScoresByUser_Handler,
		},
		{
			MethodName: "GetScoresByTeam",
			Handler:    _ScoringService_GetScoresByTeam_Handler,
		},
		{
			MethodName: "GetGlobalRanking",
			Handler:    _ScoringService_GetGlobalRanking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/scoring-service/scoring-service.proto",
}
